/**
 * Tailwind CSS v4 theme + legacy config emitter (Phase B.5).
 *
 * Consumes a canonical `DesignSpec` (output of the Phase A parser) and produces:
 *   1. A Tailwind v4 `@theme` block (CSS) that exposes every shadcn token as a
 *      `oklch(var(--x))` utility color, fonts, and radius steps.
 *   2. A LEGACY `tailwind.config.ts` (Tailwind v3-style) that maps the same
 *      tokens to `hsl(var(--x))` references (for projects still on v3), with
 *      `darkMode: "class"` and sensible content globs.
 *
 * OKLCH channel triples come from the already-tested color-engine, so the
 * values are consistent with css-variables.ts and the WCAG math. No external
 * color lib required (offline).
 */

import type { DesignSpec } from "../spec/types.ts";
import { oklchChannels, bestOnSurface } from "../transformers/color-engine.ts";
import { specToBrandTokens } from "./adapter.ts";
import type { BrandTokens } from "../brands/tokens.ts";

/** shadcn token name -> which palette field drives it (and whether it needs a
 * contrast-inferred foreground). */
const SHADCN_TOKENS: Array<{
  name: string;
  color: (s: DesignSpec) => string;
  /** if true, emit a `-foreground` paired token via contrast inference. */
  withFg?: boolean;
}> = [
  { name: "background", color: (s) => s.colors.background },
  { name: "foreground", color: (s) => s.colors.foreground },
  { name: "card", color: (s) => s.colors.background, withFg: true },
  { name: "popover", color: (s) => s.colors.background, withFg: true },
  { name: "primary", color: (s) => s.colors.primary, withFg: true },
  { name: "secondary", color: (s) => s.colors.secondary, withFg: true },
  { name: "muted", color: (s) => s.colors.muted, withFg: true },
  { name: "accent", color: (s) => s.colors.accent, withFg: true },
  { name: "destructive", color: (s) => s.colors.destructive, withFg: true },
  { name: "border", color: (s) => s.colors.border },
  { name: "input", color: (s) => s.colors.border },
  { name: "ring", color: (s) => s.colors.primary },
];

function fgFor(color: string, explicit?: string): string {
  return explicit && explicit.trim() ? explicit : bestOnSurface(color);
}

/** Emit the Tailwind v4 `@theme` block for a spec. */
export function emitTailwindV4Theme(spec: DesignSpec): string {
  const lines: string[] = ["@import \"tailwindcss\";", "", "@theme {"];
  for (const t of SHADCN_TOKENS) {
    const col = t.color(spec);
    lines.push(`  --color-${t.name}: oklch(${oklchChannels(col)});`);
    if (t.withFg) {
      const explicit =
        t.name === "primary"
          ? spec.colors.onPrimary
          : t.name === "secondary"
            ? spec.colors.onSecondary
            : t.name === "accent"
              ? spec.colors.onAccent
                : t.name === "muted"
                  ? spec.colors.onMuted
                  : t.name === "destructive"
                    ? spec.colors.onDestructive
                    : t.name === "card" || t.name === "popover"
                      ? spec.colors.foreground
                      : undefined;
      lines.push(`  --color-${t.name}-foreground: oklch(${oklchChannels(fgFor(col, explicit))});`);
    }
  }
  const r = spec.elevation.radius;
  lines.push(`  --radius-lg: ${r};`);
  lines.push(`  --radius-md: calc(${r} - 2px);`);
  lines.push(`  --radius-sm: calc(${r} - 4px);`);
  lines.push(`  --font-heading: ${spec.typography.heading.fontFamily}, ui-sans-serif, system-ui, sans-serif;`);
  lines.push(`  --font-body: ${spec.typography.body.fontFamily}, ui-sans-serif, system-ui, sans-serif;`);
  lines.push("}");
  return lines.join("\n") + "\n";
}

/**
 * Emit a legacy Tailwind v3 `tailwind.config.ts` that references the CSS vars
 * (so it pairs with the shadcn css-variables output). Kept for v3 codebases.
 */
export function emitTailwindConfigLegacy(spec: DesignSpec): string {
  const b: BrandTokens = specToBrandTokens(spec);
  const colorRefs = SHADCN_TOKENS.map((t) => {
    const entry = `    "${t.name}": "hsl(var(--${t.name}))",`;
    if (t.withFg) {
      return [entry, `    "${t.name}-foreground": "hsl(var(--${t.name}-foreground))",`].join("\n");
    }
    return entry;
  }).join("\n");
  return `import type { Config } from "tailwindcss";

// Auto-generated by design-forge for brand: ${spec.id} (${spec.name}).
// Pair with the generated theme.css (css-variables emitter). Tailwind v3 legacy.
const config: Config = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx,vue,svelte}"],
  theme: {
    extend: {
      colors: {
${colorRefs}
      },
      radius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        heading: ["${b.typography.heading}", "ui-sans-serif", "system-ui", "sans-serif"],
        body: ["${b.typography.body}", "ui-sans-serif", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
`;
}

/** Convenience: both artifacts for a spec. */
export function generateTailwindArtifacts(spec: DesignSpec): {
  v4Theme: string;
  legacyConfig: string;
} {
  return {
    v4Theme: emitTailwindV4Theme(spec),
    legacyConfig: emitTailwindConfigLegacy(spec),
  };
}
