// AUTO-GENERATED by scripts/gen-brands.ts — do not edit by hand.
// Regenerate after changing design-md/ specs: pnpm gen:brands
import type { BrandTokens } from "./tokens.ts";

export const INGESTED: BrandTokens[] = [
  {
    "id": "coral-pop",
    "name": "Coral Pop",
    "description": "Playful consumer — coral + sky, friendly radius, only primary/secondary/neutral given.",
    "colors": {
      "background": "#FFF5F3",
      "foreground": "#0a0a0a",
      "primary": "#FB7185",
      "secondary": "#0369A1",
      "accent": "#FB7185",
      "muted": "#f0e7e5",
      "destructive": "#ef4444",
      "border": "#e2d9d7"
    },
    "radius": "1.125rem",
    "typography": {
      "heading": "Outfit",
      "body": "Nunito",
      "baseSize": 17
    }
  },
  {
    "id": "ember-fintech",
    "name": "Ember Fintech",
    "description": "Warm fintech — charcoal canvas, amber ember, minimal tokens (missing on-* and typography entirely).",
    "colors": {
      "background": "#0B0B0F",
      "foreground": "#F5F5F7",
      "primary": "#F59E0B",
      "secondary": "#3A3A42",
      "accent": "#F59E0B",
      "muted": "#19191d",
      "destructive": "#ef4444",
      "border": "#27272b"
    },
    "radius": "0.5rem",
    "typography": {
      "heading": "Inter",
      "body": "Inter",
      "baseSize": 16
    }
  },
  {
    "id": "heritage",
    "name": "Heritage",
    "description": "Architectural minimalism meets journalistic gravitas — print-inspired editorial palette.",
    "colors": {
      "background": "#F7F5F2",
      "foreground": "#1A1C1E",
      "primary": "#B8422E",
      "secondary": "#6C7278",
      "accent": "#B8422E",
      "muted": "#eae8e5",
      "destructive": "#ef4444",
      "border": "#dcdbd9"
    },
    "radius": "0.5rem",
    "typography": {
      "heading": "Public Sans",
      "body": "Public Sans",
      "baseSize": 17
    }
  },
  {
    "id": "linear-dark",
    "name": "Linear Dark",
    "description": "Productivity SaaS — near-black canvas, signature indigo, token references used throughout.",
    "colors": {
      "background": "#08090A",
      "foreground": "#E6E6E6",
      "primary": "#5E6AD2",
      "secondary": "#8A8F98",
      "accent": "#5E6AD2",
      "muted": "#151617",
      "destructive": "#ef4444",
      "border": "#232424"
    },
    "radius": "0.5rem",
    "typography": {
      "heading": "Inter",
      "body": "Inter",
      "baseSize": 16
    }
  },
  {
    "id": "mono-devtools",
    "name": "Mono Devtools",
    "description": "Developer tools — near-black, lime accent, sharp radii, custom extension keys.",
    "colors": {
      "background": "#0A0A0A",
      "foreground": "#F4F4F5",
      "primary": "#A3E635",
      "secondary": "#A1A1AA",
      "accent": "#A3E635",
      "muted": "#181818",
      "destructive": "#ef4444",
      "border": "#262626"
    },
    "radius": "0.25rem",
    "typography": {
      "heading": "JetBrains Mono",
      "body": "IBM Plex Sans",
      "baseSize": 16
    }
  },
  {
    "id": "nimbus",
    "name": "Nimbus",
    "description": "Cloud-native SaaS — airy oklch palette, no explicit foregrounds (inferred at compile time).",
    "colors": {
      "background": "oklch(98% 0.005 250)",
      "foreground": "#0a0a0a",
      "primary": "oklch(62% 0.18 250)",
      "secondary": "oklch(55% 0.03 250)",
      "accent": "oklch(62% 0.18 250)",
      "muted": "#797979",
      "destructive": "#ef4444",
      "border": "#727272"
    },
    "radius": "0.75rem",
    "typography": {
      "heading": "Geist",
      "body": "Geist",
      "baseSize": 16
    }
  },
  {
    "id": "mybrand",
    "name": "MyBrand",
    "description": "One-sentence description of the visual identity.",
    "colors": {
      "background": "#F8FAFC",
      "foreground": "#0a0a0a",
      "primary": "#2563EB",
      "secondary": "#64748B",
      "accent": "#2563EB",
      "muted": "#eaeced",
      "destructive": "#ef4444",
      "border": "#dbdddf"
    },
    "radius": "0.5rem",
    "typography": {
      "heading": "Inter",
      "body": "Inter",
      "baseSize": 16
    }
  },
  {
    "id": "verdant-health",
    "name": "Verdant Health",
    "description": "Eco / health — off-white + forest green, rounded, full token set with all on-* keys.",
    "colors": {
      "background": "#F0FDF4",
      "foreground": "#14532D",
      "primary": "#15803D",
      "secondary": "#4ADE80",
      "accent": "#15803D",
      "muted": "#e3f3e8",
      "destructive": "#ef4444",
      "border": "#BBF7D0"
    },
    "radius": "0.875rem",
    "typography": {
      "heading": "Fraunces",
      "body": "Nunito",
      "baseSize": 17
    }
  }
];
