// AUTO-GENERATED by scripts/gen-brands.ts — do not edit by hand.
// Regenerate after changing design-md/ specs: pnpm gen:brands
import type { BrandTokens } from "./tokens.ts";

export const INGESTED: BrandTokens[] = [
  {
    "id": "coral-pop",
    "name": "Coral Pop",
    "description": "Playful consumer — coral + sky, friendly radius, only primary/secondary/neutral given.",
    "colors": {
      "background": "#fff5f3",
      "foreground": "#0a0a0a",
      "primary": "#fb7185",
      "secondary": "#0369a1",
      "accent": "#fb7185",
      "muted": "#f0e7e5",
      "destructive": "#ef4444",
      "border": "#e2d9d7"
    },
    "radius": "1.125rem",
    "typography": {
      "heading": "Outfit",
      "body": "Nunito",
      "baseSize": 17
    }
  },
  {
    "id": "ember-fintech",
    "name": "Ember Fintech",
    "description": "Warm fintech — charcoal canvas, amber ember, minimal tokens (missing on-* and typography entirely).",
    "colors": {
      "background": "#0b0b0f",
      "foreground": "#f5f5f7",
      "primary": "#f59e0b",
      "secondary": "#3a3a42",
      "accent": "#f59e0b",
      "muted": "#19191d",
      "destructive": "#ef4444",
      "border": "#27272b"
    },
    "radius": "0.5rem",
    "typography": {
      "heading": "Inter",
      "body": "Inter",
      "baseSize": 16
    }
  },
  {
    "id": "heritage",
    "name": "Heritage",
    "description": "Architectural minimalism meets journalistic gravitas — print-inspired editorial palette.",
    "colors": {
      "background": "#f7f5f2",
      "foreground": "#1a1c1e",
      "primary": "#b8422e",
      "secondary": "#6c7278",
      "accent": "#b8422e",
      "muted": "#eae8e5",
      "destructive": "#ef4444",
      "border": "#dcdbd9"
    },
    "radius": "0.5rem",
    "typography": {
      "heading": "Public Sans",
      "body": "Public Sans",
      "baseSize": 17
    }
  },
  {
    "id": "linear-dark",
    "name": "Linear Dark",
    "description": "Productivity SaaS — near-black canvas, signature indigo, token references used throughout.",
    "colors": {
      "background": "#08090a",
      "foreground": "#e6e6e6",
      "primary": "#5e6ad2",
      "secondary": "#8a8f98",
      "accent": "#5e6ad2",
      "muted": "#151617",
      "destructive": "#ef4444",
      "border": "#232424"
    },
    "radius": "0.5rem",
    "typography": {
      "heading": "Inter",
      "body": "Inter",
      "baseSize": 16
    }
  },
  {
    "id": "mono-devtools",
    "name": "Mono Devtools",
    "description": "Developer tools — near-black, lime accent, sharp radii, custom extension keys.",
    "colors": {
      "background": "#0a0a0a",
      "foreground": "#f4f4f5",
      "primary": "#a3e635",
      "secondary": "#a1a1aa",
      "accent": "#a3e635",
      "muted": "#181818",
      "destructive": "#ef4444",
      "border": "#262626"
    },
    "radius": "0.25rem",
    "typography": {
      "heading": "JetBrains Mono",
      "body": "IBM Plex Sans",
      "baseSize": 16
    }
  },
  {
    "id": "nimbus",
    "name": "Nimbus",
    "description": "Cloud-native SaaS — airy oklch palette, no explicit foregrounds (inferred at compile time).",
    "colors": {
      "background": "oklch(98% 0.005 250)",
      "foreground": "#0a0a0a",
      "primary": "oklch(62% 0.18 250)",
      "secondary": "oklch(55% 0.03 250)",
      "accent": "oklch(62% 0.18 250)",
      "muted": "#797979",
      "destructive": "#ef4444",
      "border": "#727272"
    },
    "radius": "0.75rem",
    "typography": {
      "heading": "Geist",
      "body": "Geist",
      "baseSize": 16
    }
  },
  {
    "id": "mybrand",
    "name": "MyBrand",
    "description": "One-sentence description of the visual identity.",
    "colors": {
      "background": "#f8fafc",
      "foreground": "#0a0a0a",
      "primary": "#2563eb",
      "secondary": "#64748b",
      "accent": "#2563eb",
      "muted": "#eaeced",
      "destructive": "#ef4444",
      "border": "#dbdddf"
    },
    "radius": "0.5rem",
    "typography": {
      "heading": "Inter",
      "body": "Inter",
      "baseSize": 16
    }
  },
  {
    "id": "verdant-health",
    "name": "Verdant Health",
    "description": "Eco / health — off-white + forest green, rounded, full token set with all on-* keys.",
    "colors": {
      "background": "#f0fdf4",
      "foreground": "#14532d",
      "primary": "#15803d",
      "secondary": "#4ade80",
      "accent": "#15803d",
      "muted": "#e3f3e8",
      "destructive": "#ef4444",
      "border": "#bbf7d0"
    },
    "radius": "0.875rem",
    "typography": {
      "heading": "Fraunces",
      "body": "Nunito",
      "baseSize": 17
    }
  }
];
