#!/usr/bin/env -S npx tsx
// Build-time codegen: ingest DESIGN.md specs (Node fs) and write a browser-safe
// TS artifact so the Vite preview (no node:fs) can resolve ingested brands.
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { ingestDir } from "../src/brands/ingest.ts";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const specDir = process.argv[2] || path.join(root, "design-md");
const out = path.join(root, "src", "brands", "ingested.ts");

const res = ingestDir(specDir);
const banner =
  "// AUTO-GENERATED by scripts/gen-brands.ts — do not edit by hand.\n" +
  "// Regenerate after changing design-md/ specs: pnpm gen:brands\n" +
  'import type { BrandTokens } from "./tokens.ts";\n\n' +
  "export const INGESTED: BrandTokens[] = ";
fs.writeFileSync(out, banner + JSON.stringify(res.brands, null, 2) + ";\n");
console.log(`Wrote ${res.brands.length} ingested brands -> ${out} (from ${res.files} .md files)`);
for (const w of res.warnings) console.log(`  ! ${w}`);
