#!/usr/bin/env -S npx tsx
// Build-time codegen: ingest DESIGN.md specs (Node fs) and write browser-safe
// TS artifacts so the Vite preview (no node:fs) can resolve ingested brands
// and synthesize components per-spec.
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { ingestDirSpecs, ingestAndWriteSpecs } from "../src/brands/ingest.ts";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const specDir = process.argv[2] || path.join(root, "design-md");
const out = path.join(root, "src", "brands", "ingested.ts");
const outSpecs = path.join(root, "src", "brands", "ingested-specs.ts");

const res = await ingestDirSpecs(specDir);
const banner =
  "// AUTO-GENERATED by scripts/gen-brands.ts — do not edit by hand.\n" +
  "// Regenerate after changing design-md/ specs: pnpm gen:brands\n" +
  'import type { BrandTokens } from "./tokens.ts";\n\n' +
  "export const INGESTED: BrandTokens[] = ";
fs.writeFileSync(out, banner + JSON.stringify(res.brands, null, 2) + ";\n");

const specRes = await ingestAndWriteSpecs(specDir, outSpecs);

console.log(`Wrote ${res.brands.length} ingested brands -> ${out} (from ${res.files} .md files)`);
console.log(`Wrote ${specRes.specs.length} ingested specs -> ${outSpecs}`);
for (const w of res.warnings) console.log(`  ! ${w}`);
